# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MOMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MOMO
  pod 'SwiftGen', '~> 6.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint'	
  pod 'FSCalendar'

end
